version: '2.2'

services:
  bank-api:
    container_name: bank-api
    image: dev/bank_api
    build: 
      context: .
      network: host
    ports:
      - "3000:3000"
    extra_hosts:
      - "cloudvps:45.62.246.57"